// lib/core/firebase/firebase_options.dart
// ============================================================
// THIS FILE IS AUTO-GENERATED BY FLUTTERFIRE CLI
// DO NOT MANUALLY EDIT
//
// HOW TO GENERATE THIS FILE:
// ─────────────────────────────────────────
// 1. Install FlutterFire CLI:
//    dart pub global activate flutterfire_cli
//
// 2. In the mobile/ folder, run:
//    flutterfire configure
//
// 3. Select your Firebase project: rozgarx-ai
//
// 4. Select platform: android
//
// 5. This file will be auto-generated with your real config.
//
// ─────────────────────────────────────────
// PLACEHOLDER BELOW — Replace by running flutterfire configure
// ─────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not supported');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  // ⚠️  REPLACE THESE VALUES with output from: flutterfire configure
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',                    // ← Replace
    appId: '1:000000000000:android:0000000000', // ← Replace
    messagingSenderId: '000000000000',          // ← Replace
    projectId: 'rozgarx-ai',                   // ← Replace if different
    storageBucket: 'rozgarx-ai.appspot.com',   // ← Replace if different
  );
}
